name: Build and Package Windows EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        venv\Scripts\activate
        pip3 install -U -r requirements.txt

    - name: Build Main with PyInstaller
      run: |
        venv\Scripts\activate
        pyinstaller Scorebug.spec

    - name: Build Console/Debug with PyInstaller
      run: |
        venv\Scripts\activate
        pyinstaller ScorebugConsole.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Scorebug
        path: dist/
